#python -m torch.distributed.launch --nproc_per_node 1 
python main.py \
    --seed 2 \
    --name crowd \
    --dataset crowd \
    --num-labeled 10000 \
    --expand-labels \
    --total-steps 300000 \
    --eval-step 1000 \
    --randaug 2 16 \
    --batch-size 4 \
    --teacher_lr 1e-5 \
    --student_lr 1e-5 \
    --weight-decay 5e-4 \
    --nesterov \
    --mu 1 \
    --temperature 0.7 \
    --threshold 0.6 \
    --lambda-u 8 \
    --warmup-steps 5000 \
    --uda-steps 5000 \
    --student-wait-steps 3000 \
    --teacher-dropout 0.2 \
    --student-dropout 0.2 \
    --finetune-epochs 250 \
    --finetune-batch-size 2 \
    --finetune-lr 3e-5 \
    --finetune-weight-decay 0 \
    --finetune-momentum 0.9 \
    --home "/work/wycho/2023bigdataproject/src/" \
    --train_l_data "npydata/qnrf_train.npy" \
    --train_ul_data "npydata/ShanghaiA_train.npy" \
    --test_l_data "/npydata/qnrf_test.npy" \
    --use_wandb \
    --description "1st" \
    --amp